### ISSUE TITLE
Why is aurelia-materialize-bridge in quotes vs regular js object with no quotes

### ISSUE THREAD

**Issue by delebash** [Thanood/md-webpack-skeleton#1]
Why is this line  `'aurelia-materialize-bridge': [ 'aurelia-materialize-bridge' ]` key in quotes vs a regular js object where the key is not in quotes?

The line above is standard js object

```
materialize: [
    'materialize-css'
  ],
```

Can you explain what this difference means?

Thanks for this skeleton

**Comment by Thanood** [comment]
It's a standard js object but its key contains dashes for readability. :-)
In that case you need quotes. But the entry could actually be anything. It's just more readable.

**Comment by delebash** [comment]
Duh, ok I feel real stupid right now.  I was too caught up in the new webpack config and how you added  md guess I wasn't thinking clearly.

Thanks :)
